name: PHP Composer

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # 秘密鍵を設置
      - name: ssh key generate
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY_MASTER }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub

      # ssh rsync実行
      # -a コピー元のディレクトリを再帰的にオーナー・グループ・パーミッション・タイムスタンプをそのままコピーします。
      # -h でファイルサイズの視認性をよくする。
      # -v 詳細を出力する。
      # -z 圧縮転送
      # -e ssh指定
      - name: Deploy
        run: rsync -ahvz -e "ssh -i ~/.ssh/id_rsa.pub -p ${{ secrets.SSH_PORT_MASTER }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USERNAME_MASTER }}@${{ secrets.SSH_HOST_MASTER }}:${{ secrets.SSH_PATH_MASTER }}

